# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 4.3

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /opt/homebrew/bin/cmake

# The command to remove a file.
RM = /opt/homebrew/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /Users/ronny/Desktop/AI/Usul

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /Users/ronny/Desktop/AI/Usul

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake cache editor..."
	/opt/homebrew/bin/ccmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake to regenerate build system..."
	/opt/homebrew/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/ronny/Desktop/AI/Usul/CMakeFiles /Users/ronny/Desktop/AI/Usul//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/ronny/Desktop/AI/Usul/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named Usul

# Build rule for target.
Usul: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 Usul
.PHONY : Usul

# fast build rule for target.
Usul/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Usul.dir/build.make CMakeFiles/Usul.dir/build
.PHONY : Usul/fast

src/main.o: src/main.cpp.o
.PHONY : src/main.o

# target to build an object file
src/main.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Usul.dir/build.make CMakeFiles/Usul.dir/src/main.cpp.o
.PHONY : src/main.cpp.o

src/main.i: src/main.cpp.i
.PHONY : src/main.i

# target to preprocess a source file
src/main.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Usul.dir/build.make CMakeFiles/Usul.dir/src/main.cpp.i
.PHONY : src/main.cpp.i

src/main.s: src/main.cpp.s
.PHONY : src/main.s

# target to generate assembly for a file
src/main.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Usul.dir/build.make CMakeFiles/Usul.dir/src/main.cpp.s
.PHONY : src/main.cpp.s

src/neural/layer.o: src/neural/layer.cpp.o
.PHONY : src/neural/layer.o

# target to build an object file
src/neural/layer.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Usul.dir/build.make CMakeFiles/Usul.dir/src/neural/layer.cpp.o
.PHONY : src/neural/layer.cpp.o

src/neural/layer.i: src/neural/layer.cpp.i
.PHONY : src/neural/layer.i

# target to preprocess a source file
src/neural/layer.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Usul.dir/build.make CMakeFiles/Usul.dir/src/neural/layer.cpp.i
.PHONY : src/neural/layer.cpp.i

src/neural/layer.s: src/neural/layer.cpp.s
.PHONY : src/neural/layer.s

# target to generate assembly for a file
src/neural/layer.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Usul.dir/build.make CMakeFiles/Usul.dir/src/neural/layer.cpp.s
.PHONY : src/neural/layer.cpp.s

src/neural/neuron.o: src/neural/neuron.cpp.o
.PHONY : src/neural/neuron.o

# target to build an object file
src/neural/neuron.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Usul.dir/build.make CMakeFiles/Usul.dir/src/neural/neuron.cpp.o
.PHONY : src/neural/neuron.cpp.o

src/neural/neuron.i: src/neural/neuron.cpp.i
.PHONY : src/neural/neuron.i

# target to preprocess a source file
src/neural/neuron.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Usul.dir/build.make CMakeFiles/Usul.dir/src/neural/neuron.cpp.i
.PHONY : src/neural/neuron.cpp.i

src/neural/neuron.s: src/neural/neuron.cpp.s
.PHONY : src/neural/neuron.s

# target to generate assembly for a file
src/neural/neuron.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Usul.dir/build.make CMakeFiles/Usul.dir/src/neural/neuron.cpp.s
.PHONY : src/neural/neuron.cpp.s

src/neural/node.o: src/neural/node.cpp.o
.PHONY : src/neural/node.o

# target to build an object file
src/neural/node.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Usul.dir/build.make CMakeFiles/Usul.dir/src/neural/node.cpp.o
.PHONY : src/neural/node.cpp.o

src/neural/node.i: src/neural/node.cpp.i
.PHONY : src/neural/node.i

# target to preprocess a source file
src/neural/node.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Usul.dir/build.make CMakeFiles/Usul.dir/src/neural/node.cpp.i
.PHONY : src/neural/node.cpp.i

src/neural/node.s: src/neural/node.cpp.s
.PHONY : src/neural/node.s

# target to generate assembly for a file
src/neural/node.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Usul.dir/build.make CMakeFiles/Usul.dir/src/neural/node.cpp.s
.PHONY : src/neural/node.cpp.s

src/optim/autodiff.o: src/optim/autodiff.cpp.o
.PHONY : src/optim/autodiff.o

# target to build an object file
src/optim/autodiff.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Usul.dir/build.make CMakeFiles/Usul.dir/src/optim/autodiff.cpp.o
.PHONY : src/optim/autodiff.cpp.o

src/optim/autodiff.i: src/optim/autodiff.cpp.i
.PHONY : src/optim/autodiff.i

# target to preprocess a source file
src/optim/autodiff.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Usul.dir/build.make CMakeFiles/Usul.dir/src/optim/autodiff.cpp.i
.PHONY : src/optim/autodiff.cpp.i

src/optim/autodiff.s: src/optim/autodiff.cpp.s
.PHONY : src/optim/autodiff.s

# target to generate assembly for a file
src/optim/autodiff.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Usul.dir/build.make CMakeFiles/Usul.dir/src/optim/autodiff.cpp.s
.PHONY : src/optim/autodiff.cpp.s

src/optim/gradient_descent.o: src/optim/gradient_descent.cpp.o
.PHONY : src/optim/gradient_descent.o

# target to build an object file
src/optim/gradient_descent.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Usul.dir/build.make CMakeFiles/Usul.dir/src/optim/gradient_descent.cpp.o
.PHONY : src/optim/gradient_descent.cpp.o

src/optim/gradient_descent.i: src/optim/gradient_descent.cpp.i
.PHONY : src/optim/gradient_descent.i

# target to preprocess a source file
src/optim/gradient_descent.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Usul.dir/build.make CMakeFiles/Usul.dir/src/optim/gradient_descent.cpp.i
.PHONY : src/optim/gradient_descent.cpp.i

src/optim/gradient_descent.s: src/optim/gradient_descent.cpp.s
.PHONY : src/optim/gradient_descent.s

# target to generate assembly for a file
src/optim/gradient_descent.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Usul.dir/build.make CMakeFiles/Usul.dir/src/optim/gradient_descent.cpp.s
.PHONY : src/optim/gradient_descent.cpp.s

src/util/rand.o: src/util/rand.cpp.o
.PHONY : src/util/rand.o

# target to build an object file
src/util/rand.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Usul.dir/build.make CMakeFiles/Usul.dir/src/util/rand.cpp.o
.PHONY : src/util/rand.cpp.o

src/util/rand.i: src/util/rand.cpp.i
.PHONY : src/util/rand.i

# target to preprocess a source file
src/util/rand.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Usul.dir/build.make CMakeFiles/Usul.dir/src/util/rand.cpp.i
.PHONY : src/util/rand.cpp.i

src/util/rand.s: src/util/rand.cpp.s
.PHONY : src/util/rand.s

# target to generate assembly for a file
src/util/rand.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Usul.dir/build.make CMakeFiles/Usul.dir/src/util/rand.cpp.s
.PHONY : src/util/rand.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... Usul"
	@echo "... src/main.o"
	@echo "... src/main.i"
	@echo "... src/main.s"
	@echo "... src/neural/layer.o"
	@echo "... src/neural/layer.i"
	@echo "... src/neural/layer.s"
	@echo "... src/neural/neuron.o"
	@echo "... src/neural/neuron.i"
	@echo "... src/neural/neuron.s"
	@echo "... src/neural/node.o"
	@echo "... src/neural/node.i"
	@echo "... src/neural/node.s"
	@echo "... src/optim/autodiff.o"
	@echo "... src/optim/autodiff.i"
	@echo "... src/optim/autodiff.s"
	@echo "... src/optim/gradient_descent.o"
	@echo "... src/optim/gradient_descent.i"
	@echo "... src/optim/gradient_descent.s"
	@echo "... src/util/rand.o"
	@echo "... src/util/rand.i"
	@echo "... src/util/rand.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

