// neural
#include <neural/layer.hpp>
#include <neural/neuron.hpp>
#include <neural/node.hpp>
// optim
#include <optim/autodiff.hpp>
#include <optim/gradient_descent.hpp>
// util
#include <util/rand.hpp>
